# Generated by Django 5.2.8 on 2025-12-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.difficultytype')),
                ('tags', models.ManyToManyField(blank=True, to='challenges.challengetag')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengetype')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('weekly_deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('xp_gained', models.IntegerField()),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.userchallenge')),
            ],
        ),
    ]
