# Generated by Django 5.2.8 on 2025-12-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'definition')},
        ),
    ]
