# Generated by Django 5.2.8 on 2025-12-20 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_userchallenge_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallenge',
            name='started_at',
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
