# Generated by Django 5.2.8 on 2025-12-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_userchallenge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
