# Generated by Django 5.2.8 on 2025-12-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_userchallenge_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengehistory',
            name='xp_gained',
            field=models.IntegerField(default=0),
        ),
    ]
