# Generated by Django 5.2.8 on 2025-12-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_userchallenge_is_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together=set(),
        ),
    ]
