# Generated by Django 5.2.8 on 2025-12-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_challengehistory_xp_gained'),
        ('gamification', '0005_delete_modulexpconfig_alter_xplog_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengehistory',
            name='user_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='challenges.userchallenge'),
        ),
        migrations.AlterField(
            model_name='challengetype',
            name='name',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='challenge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenges.challengetype'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='gamification.user'),
        ),
    ]
