# Generated by Django 5.2.8 on 2025-12-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challengehistory_user_challenge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeHistory',
        ),
    ]
