# Generated by Django 5.2.8 on 2025-12-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficultytype',
            name='xp_value',
        ),
        migrations.AlterField(
            model_name='difficultytype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
