# Generated by Django 5.2.8 on 2025-12-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_difficultytype_xp_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultytype',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
