# Generated by Django 5.2.8 on 2025-12-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='motivation_reason',
            field=models.TextField(),
        ),
    ]
