# Generated by Django 5.2.8 on 2025-12-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='current_streak',
        ),
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#908bab', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='motivation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='HabitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'empty'), (1, 'skipped'), (2, 'completed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='HabitTracking',
        ),
    ]
