# Generated by Django 5.2.8 on 2025-12-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_remove_habit_color_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitday',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitday',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='habits.habit'),
        ),
    ]
