# Generated by Django 5.2.8 on 2025-12-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalperiod',
            name='default_xp',
        ),
    ]
