# Generated by Django 5.2.8 on 2025-12-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goalperiod_default_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalhistory',
            name='xp_gained',
            field=models.IntegerField(default=0),
        ),
    ]
