# Generated by Django 5.2.8 on 2025-12-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goalhistory_xp_gained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='motivation_reason',
            field=models.TextField(),
        ),
    ]
