# Generated by Django 5.2.8 on 2025-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_motivation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalperiod',
            name='name',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, unique=True),
        ),
    ]
