# Generated by Django 5.2.8 on 2026-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_completed_at_goal_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
