# Generated by Django 5.2.8 on 2026-02-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='ceiling_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='floor_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_goal',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goals.goal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
