# Generated by Django 5.2.8 on 2026-02-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_difficultytype_order'),
        ('gamification', '0006_user_xp_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('habit_days', 'X days of specific habit'), ('any_habit_days', 'X days of any habit'), ('habit_streak', 'X day streak of specific habit'), ('any_habit_streak', 'X day streak of any habit'), ('goal_completed', 'X completed goals'), ('goal_completed_by_period', 'X completed goals by period'), ('todo_completed', 'X completed todos'), ('notes_count', 'Create X notes'), ('mood_logged_days', 'Log mood X days'), ('specific_mood_count', 'Log specific mood X times'), ('sobriety_duration', 'X duration of specific sobriety'), ('any_sobriety_duration', 'X duration of any sobriety'), ('level_reached', 'Reach level'), ('xp_reached', 'Reach XP'), ('manual', 'Manual unlock')], max_length=40)),
                ('condition_config', models.JSONField(default=dict)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.difficultytype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_achievements', to='gamification.user')),
            ],
            options={
                'ordering': ['difficulty__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
                ('target_value', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='gamification.user')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
