# Generated by Django 5.2.8 on 2026-01-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todotask_completed_at_delete_todohistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='is_default',
        ),
    ]
