# Generated by Django 5.2.8 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_todotask_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='todotask',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
