# Generated by Django 5.2.8 on 2025-12-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleXPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('random', 'Random')], max_length=30, unique=True)),
                ('base_xp', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ModuleDefinition',
        ),
    ]
