# Generated by Django 5.2.8 on 2025-12-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_modulexpconfig_delete_moduledefinition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulexpconfig',
            old_name='base_xp',
            new_name='multiplier',
        ),
    ]
