# Generated by Django 5.2.8 on 2025-12-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_rename_base_xp_modulexpconfig_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulexpconfig',
            name='multiplier',
            field=models.FloatField(),
        ),
    ]
