# Generated by Django 5.2.8 on 2025-12-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_modulexpconfig_multiplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleXPConfig',
        ),
        migrations.AlterField(
            model_name='xplog',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
