# Generated by Django 5.2.8 on 2025-12-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_delete_modulexpconfig_alter_xplog_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
