# Generated by Django 5.2.8 on 2026-02-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0006_user_xp_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad'), ('terrible', 'Terrible')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
