# Generated by Django 5.2.8 on 2025-12-16 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification', '0002_modulexpconfig_delete_moduledefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('randomizer', 'Randomizer'), ('gamification', 'Gamification'), ('notes', 'Notes')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
    ]
