# Generated by Django 5.2.8 on 2025-12-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_modulexpconfig_multiplier'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('module_dependency', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
