# Generated by Django 5.2.8 on 2025-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_dashboardtile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledefinition',
            name='module',
            field=models.CharField(choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('random', 'Random'), ('gamification', 'Gamification'), ('notes', 'Notes')], max_length=30),
        ),
    ]
