# Generated by Django 5.2.8 on 2025-12-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_moduledefinition_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtile',
            name='key',
            field=models.CharField(choices=[('level_gamification', 'Level gamification'), ('biggest_streak', 'Biggest streak'), ('random_habit', 'Random habit'), ('random_todo', 'Random todo'), ('goal_week', 'Week goal'), ('goal_month', 'Month goal'), ('goal_year', 'Year goal'), ('daily_challenge', 'Daily challenge'), ('weekly_challenge', 'Weekly challenge'), ('random_note', 'Random note')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardtile',
            name='module_dependency',
            field=models.CharField(blank=True, choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('random', 'Random'), ('gamification', 'Gamification'), ('notes', 'Notes')], max_length=30, null=True),
        ),
    ]
