# Generated by Django 5.2.8 on 2026-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_dashboardtile_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtile',
            name='module_dependency',
            field=models.CharField(blank=True, choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('random', 'Random'), ('gamification', 'Gamification'), ('notes', 'Notes'), ('mood', 'Mood'), ('sobriety', 'Sobriety')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='moduledefinition',
            name='module',
            field=models.CharField(choices=[('habits', 'Habits'), ('challenges', 'Challenges'), ('todos', 'Todos'), ('goals', 'Goals'), ('random', 'Random'), ('gamification', 'Gamification'), ('notes', 'Notes'), ('mood', 'Mood'), ('sobriety', 'Sobriety')], max_length=30),
        ),
    ]
