# Generated by Django 5.2.8 on 2026-02-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_user_xp_multiplier'),
        ('settings', '0005_alter_dashboardtile_module_dependency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hide_quick_add_difficulty', 'Hide quick add difficulty')], max_length=50)),
                ('value', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.user')),
            ],
            options={
                'unique_together': {('user', 'key')},
            },
        ),
    ]
