# Generated by Django 5.2.8 on 2026-02-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='key',
            field=models.CharField(choices=[('hide_quick_add_difficulty', 'Hide quick add difficulty'), ('hide_todo_completed_toggle', 'Hide todo completed toggle'), ('default_todo_category_id', 'Default todo category')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
